Currently getting NoClassDefFoundError when trying to run jar. Meanwhile, updated additionalCourseInfoWindow so that it is able to generate a hardcoded table. Will eventually update so that it prints all sections of a course as well as an add button to add to ShoppingCart for User.